"""updated tables

Revision ID: d0901d523034
Revises: a70e1a85b931
Create Date: 2023-05-10 12:12:24.524298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0901d523034'
down_revision = 'a70e1a85b931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('for_sale',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('for_sale',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
